<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [91]:
import numpy as np

In [92]:
array_1D = np.arange(10)
print(array_1D)


[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [93]:
array_2D = array_1D.reshape(2,5)
print(array_2D)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [94]:
array_uni_3 = np.array([0, 2, 0, 3, 0, 4, 0])
print(array_uni_3)
lista_indices_0= []
for indice, elemento in enumerate(array_uni_3):
    if elemento ==0:
        lista_indices_0.append(indice)
    else:
        continue
print(f'Los indices de los elementos 0 son: {lista_indices_0}')


[0 2 0 3 0 4 0]
Los indices de los elementos 0 son: [0, 2, 4, 6]


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [95]:
array_bi_4 = np.random.rand(3,3)
print(array_bi_4)

[[0.24857964 0.67477567 0.01155702]
 [0.54717221 0.85979472 0.16599271]
 [0.21560696 0.93449665 0.30275095]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [96]:
array_bi_5 = np.round(np.random.rand(2,5), 2)
print(array_bi_5)


[[0.03 0.85 0.26 0.84 0.29]
 [0.52 0.74 0.22 0.69 0.33]]


In [97]:
#maximo
print(f'El máximo del array es {np.max(array_bi_5)}')

#mínimo
print(f'El mínimo del array es {np.min(array_bi_5)}')

El máximo del array es 0.85
El mínimo del array es 0.03


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [98]:
array_uni_invertir = np.random.randint(0,10, (1,5))
print(array_uni_invertir)

[[2 0 5 9 8]]


In [99]:
array_invertido = np.transpose(array_uni_invertir)
print(array_invertido)

[[2]
 [0]
 [5]
 [9]
 [8]]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [100]:
array_tri_2 = np.random.randint(0,25, (2,3,4))
print(array_tri_2)

[[[23 15  4 24]
  [15 10 24 13]
  [ 2 13  2  0]]

 [[13  3 10 12]
  [15 23 14  2]
  [13  4  3 14]]]


In [108]:
#Selecciona el primer 15 del array:

print(array_tri_2[0, 0, 1])

15


In [102]:
# Selecciona todos los elementos del primer array. 

print(array_tri_2[0,:,:])

[[23 15  4 24]
 [15 10 24 13]
 [ 2 13  2  0]]


In [103]:
# Selecciona la última fila del último array

print(array_tri_2[1,2:,:])

[[13  4  3 14]]



#### Ejercicio 8 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [104]:
array_tri_3 = np.random.randint(0,31, (3,2,5))
print(array_tri_3)

[[[25  6 13 20  5]
  [12 29 18  7 15]]

 [[18 23 16 21  7]
  [ 9  5 28  5 10]]

 [[ 5  6  2 27  5]
  [ 3 29  3 28 11]]]


In [105]:
#Selecciona el subarray que contiene todas las filas de los dos últimos arrays.
print(array_tri_3[1:,:,:])

[[[18 23 16 21  7]
  [ 9  5 28  5 10]]

 [[ 5  6  2 27  5]
  [ 3 29  3 28 11]]]


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [106]:
array_tri_4 = np.random.randint(0,25, (4,3,2))
print(array_tri_4)

[[[13 23]
  [18  6]
  [ 0 12]]

 [[21  5]
  [18  4]
  [23 12]]

 [[24 18]
  [12  3]
  [ 7 18]]

 [[11  6]
  [18 21]
  [ 6  5]]]


In [ ]:
#- Cambia todos los valores del último array a `-1`.
for indice_array,elemento_array in enumerate(array_tri_4):
    #print(indice)
    #print(elemento)
    if indice_array ==3:
        #print(elemento_array)
        for indice_lista, elemento_lista in enumerate(elemento_array):
            #print(elemento_lista)
            for indice_columna, elemento_columna in enumerate(elemento_lista):
                #print(elemento_columna)
                array_tri_4[indice_array][indice_lista][indice_columna]= -1
            
print(array_tri_4)

[[[13 23]
  [18  6]
  [ 0 12]]

 [[21  5]
  [18  4]
  [23 12]]

 [[24 18]
  [12  3]
  [ 7 18]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 10 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [113]:
array_tri_5 = np.random.randint(-10,14, (2,4,3))
print(array_tri_5)


[[[ 10  -3   2]
  [  2  -1   6]
  [  4   8  -4]
  [ -4   2   3]]

 [[ -5   2   3]
  [ -7 -10   2]
  [ -2   1   3]
  [  0   5   7]]]


In [ ]:
#Selecciona todos los elementos mayores a `5`.
mascara = array_tri_5>5
elementos_mayores_5 = array_tri_5[mascara]
print(elementos_mayores_5)

[10  6  8  7]


In [ ]:
#Reemplaza todos los elementos negativos por `0`.
resultado_no_negativos = np.where((array_tri_5<0),0,array_tri_5)
print(resultado_no_negativos)

[[[10  0  2]
  [ 2  0  6]
  [ 4  8  0]
  [ 0  2  3]]

 [[ 0  2  3]
  [ 0  0  2]
  [ 0  1  3]
  [ 0  5  7]]]


#### Ejercicio 11 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [144]:
array_tri_6 = np.random.randint(1,28, (3,3,3))
print(array_tri_6)

[[[25  3  3]
  [ 3 10 22]
  [ 1 20  5]]

 [[25 25  1]
  [21 23 27]
  [26 26 20]]

 [[22 10 12]
  [ 6  5  6]
  [25 20 27]]]


In [145]:
# Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

print(array_tri_6[1:2,:,:2])

[[[25 25]
  [21 23]
  [26 26]]]


In [154]:
#Selecciona todos los elementos del tercer array que sean mayores que `20`.
tercer_array = array_tri_6[2,:,:]
print(f'El tercer array es:')
print(tercer_array)
condicion = tercer_array>20
elementos_mayores_20 = tercer_array[condicion]
print(f'Los elementos mayores de 20 son {elementos_mayores_20}')

El tercer array es:
[[22 10 12]
 [ 6  5  6]
 [25 20 27]]
Los elementos mayores de 20 son [22 25 27]


#### Ejercicio 12 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [160]:
array_bi_6 = np.round(np.random.rand(2,5), 2)
print(array_bi_6)
array_bi_6_corregido = np.where((array_bi_6==np.min(array_bi_6))|(array_bi_6==np.max(array_bi_6)),0,array_bi_6)
print(f'El máximo es {np.max(array_bi_6)} y el mínimo es {np.min(array_bi_6)}')
print(f'El array con 0 en el máximo y mínimo es:')
print(array_bi_6_corregido)

[[0.2  0.49 0.08 0.59 0.96]
 [0.3  0.82 0.75 0.36 0.92]]
El máximo es 0.96 y el mínimo es 0.08
El array con 0 en el máximo y mínimo es:
[[0.2  0.49 0.   0.59 0.  ]
 [0.3  0.82 0.75 0.36 0.92]]


#### Ejercicio 13 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [164]:
array_uni_4 = np.random.randint(1,101, (1,15))
print(array_uni_4)

[[99 77 70 40 20 28 62 11 28 78 42 93 68 26 34]]


In [165]:
array_uni_4_ordenado = np.sort(array_uni_4)
print(f'El array ordenado es:')
print(array_uni_4_ordenado)

El array ordenado es:
[[11 20 26 28 28 34 40 42 62 68 70 77 78 93 99]]


#### Ejercicio 14 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [166]:
array_bi_7 = np.random.randint(1,101, (4,4))
print(array_bi_7)

[[ 90  75  45  14]
 [ 52  68 100  62]
 [ 86  43  31  47]
 [ 68  18  99   9]]


In [172]:
#suma por filas
print(f'La suma por filas es:')
suma_filas = np.sum(array_bi_7, axis=1)
print(suma_filas)

#suma por columnas
print(f'La suma por columnas es:')
suma_columnas = np.sum(array_bi_7, axis=0)
print(suma_columnas)


La suma por filas es:
[224 282 207 194]
La suma por columnas es:
[296 204 275 132]


#### Ejercicio 15 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [180]:
array_bi_8 = np.random.randint(1,101, (5,5))
print(f'La matriz inicial es')
print(array_bi_8)

for indice_fila,elemento_fila in enumerate(array_bi_8):
    #print(indice_fila)
    #print(elemento_fila)
    for indice_columna, elemento_columna in enumerate(elemento_fila):
        #print(indice_columna)
        #print(elemento_columna)
        if (indice_fila==0 and indice_columna==0) or (indice_fila==4 and indice_columna==4):
            array_bi_8[indice_fila][indice_columna] = 1
        else:
            array_bi_8[indice_fila][indice_columna] = 0
print('La matriz con los bordes con 1 el interior a 0 es')
print(array_bi_8)



La matriz inicial es
[[25 30  7 89 43]
 [62 99 30 88 43]
 [31 23 16 87 25]
 [27 66 45 89 52]
 [94 67  2 75 21]]
La matriz con los bordes con 1 el interior a 0 es
[[1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]


#### Ejercicio 16 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [183]:
array_uni_5= np.random.randint(1,101, (1,11))
print(f'El array creado es:')
print(array_uni_5)

print('La media del array es:')
print(np.mean(array_uni_5))

print('La desviación estandar es:')
print(np.std(array_uni_5))

El array creado es:
[[34 45 60 42 68 41 68 42 81 73 75]]
La media del array es:
57.18181818181818
La desviación estandar es:
15.91350588090153


#### Ejercicio 17 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [192]:
array_tri_7= np.random.randint(1,25, (2,3,4))
print('El array original es')
print(array_tri_7)

print('El array con los ejes intercambiados es')
array_tri_7_intercambiado = np.transpose(array_tri_7,(2,1,0))
print(array_tri_7_intercambiado)

El array original es
[[[12 24 22 20]
  [11  8  6 12]
  [11 10 16  1]]

 [[21 21  2 21]
  [17 16 21 10]
  [18  7  2 22]]]
El array con los ejes intercambiados es
[[[12 21]
  [11 17]
  [11 18]]

 [[24 21]
  [ 8 16]
  [10  7]]

 [[22  2]
  [ 6 21]
  [16  2]]

 [[20 21]
  [12 10]
  [ 1 22]]]


#### Explicación ejercicio 17
Se ha intercambiando el número de columnas por el número de arrays. Antes teníamos 2 arrays, 4 filas y 4 columnas y ahora tenemos 4 arrays, 4 filas y 2 columnas:
- La primera columna del primer array transpuesto es la primera columna del primer array original
- La segunda columna del primera array transpuesto es la primera columna del segundo array original

- La primera columna del segundo array transpuesto es la segunda columna del primer array original
- La segunda columna del segundo array transpuesto es la segunda columna del segundo array original

- La primera columna del tercer array transpuesto es la tercera columna del primer array original
- La segunda columna del tercer array transpuesto es la tercera columna del segundo array original

- La primera columna del cuarto array transpuesto es la cuarta columna del primer array original
- La segunda columna del cuarto array transpuesto es la cuarta columna del segundo array original

#### Ejercicio 18 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [195]:
array_tri_8= np.random.randint(1,25, (3,4,2))
print('El array original es')
print(array_tri_8)

print('El array con los ejes intercambiados es')
array_tri_8_intercambiado = np.swapaxes(array_tri_8,0,1)
print(array_tri_8_intercambiado)

El array original es
[[[24 14]
  [13  2]
  [ 8 14]
  [14 21]]

 [[ 7  4]
  [ 1  8]
  [ 6  5]
  [ 3 21]]

 [[11  9]
  [11  6]
  [ 9  1]
  [ 8  3]]]
El array con los ejes intercambiados es
[[[24 14]
  [ 7  4]
  [11  9]]

 [[13  2]
  [ 1  8]
  [11  6]]

 [[ 8 14]
  [ 6  5]
  [ 9  1]]

 [[14 21]
  [ 3 21]
  [ 8  3]]]


#### Ejercicio 19- Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [198]:
array_tri_9= np.random.randint(1,25, (3,2,4))
print('El array original es')
print(array_tri_9)

print('El array con la rotación de los ejes es')
array_tri_9_intercambiado = np.transpose(array_tri_9,(2,0,1))
print(array_tri_9_intercambiado)

El array original es
[[[16 13 13 22]
  [ 3 10  6  3]]

 [[ 8  4  5 24]
  [15 12  3  3]]

 [[18  6 12 18]
  [13 14 16 10]]]
El array con la rotación de los ejes es
[[[16  3]
  [ 8 15]
  [18 13]]

 [[13 10]
  [ 4 12]
  [ 6 14]]

 [[13  6]
  [ 5  3]
  [12 16]]

 [[22  3]
  [24  3]
  [18 10]]]


#### Ejercicio 20 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`. #Sustituyo MAX por H porque solo me coge la primera vocal

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`. #Sustituyo MIN por L porque solo me coge la primera vocal


In [257]:
array_tri_10= np.random.randint(-10,10, (3,4,5))
print('El array original es')
print(array_tri_10)

array_tri_10_mediana=round(np.median(array_tri_10),0)
print(f'La mediana es {array_tri_10_mediana}')

array_tri_10_max = np.max(array_tri_10)
print(f'El máximo es {array_tri_10_max}')

array_tri_10_min = np.min(array_tri_10)
print(f'El mínimo es {array_tri_10_min}')

array_tri_10_vacio = np.empty((3,4,5), dtype=str)
#print(array_tri_10_vacio)

for indice_array,elemento_array in enumerate(array_tri_10):
    for indice_fila, elemento_fila in enumerate(elemento_array):
        for indice_columna, elemento_columna in enumerate(elemento_fila):
            #print(array_tri_10[indice_array][indice_fila][indice_columna])
            if array_tri_10[indice_array][indice_fila][indice_columna] == array_tri_10_mediana:
                array_tri_10_vacio[indice_array][indice_fila][indice_columna] = 'M'
            elif array_tri_10[indice_array][indice_fila][indice_columna] == array_tri_10_max:
                array_tri_10_vacio[indice_array][indice_fila][indice_columna] = 'H'
            elif array_tri_10[indice_array][indice_fila][indice_columna] == array_tri_10_min:
                array_tri_10_vacio[indice_array][indice_fila][indice_columna] = 'L'
            elif array_tri_10[indice_array][indice_fila][indice_columna] >array_tri_10_mediana:
                array_tri_10_vacio[indice_array][indice_fila][indice_columna] = 'X'                    
            elif array_tri_10[indice_array][indice_fila][indice_columna] <array_tri_10_mediana:
                array_tri_10_vacio[indice_array][indice_fila][indice_columna] = 'Y'
print(f'La matriz con letras es')             
print(array_tri_10_vacio)

El array original es
[[[-10  -4   2   9  -7]
  [ -4  -2  -2  -9   8]
  [  4  -9   4  -8   7]
  [  3   4  -4  -9  -2]]

 [[ -3   5   6   4   0]
  [ -2  -8  -4  -2 -10]
  [  2   4   7  -9  -3]
  [  5   3   5   3  -8]]

 [[ -1   1  -2 -10  -2]
  [ -3   6   5   4   7]
  [  5   4  -4   4   9]
  [ -8   9  -8   4   9]]]
La mediana es 0.0
El máximo es 9
El mínimo es -10
La matriz con letras es
[[['L' 'Y' 'X' 'H' 'Y']
  ['Y' 'Y' 'Y' 'Y' 'X']
  ['X' 'Y' 'X' 'Y' 'X']
  ['X' 'X' 'Y' 'Y' 'Y']]

 [['Y' 'X' 'X' 'X' 'M']
  ['Y' 'Y' 'Y' 'Y' 'L']
  ['X' 'X' 'X' 'Y' 'Y']
  ['X' 'X' 'X' 'X' 'Y']]

 [['Y' 'X' 'Y' 'L' 'Y']
  ['Y' 'X' 'X' 'X' 'X']
  ['X' 'X' 'Y' 'X' 'H']
  ['Y' 'H' 'Y' 'X' 'H']]]


#### Ejercicio 21 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [310]:
array_bi_9= np.random.randint(0,2, (4,4))
print(f'El array original es:')
print(array_bi_9)

El array original es:
[[1 1 1 1]
 [1 1 1 0]
 [1 1 0 1]
 [0 1 1 0]]


In [311]:
for indice_fila in range (0,4):
    #print(array_bi_9[indice_fila])
    fila = tuple(array_bi_9[indice_fila])
    for indice_columna in range (0,4):
        #print(array_bi_9[:,indice_columna])
        columna_en_fila = tuple(array_bi_9[:,indice_columna])
        #print(fila)
        #print(columna_en_fila)
        #print(fila == columna_en_fila)
        if fila == columna_en_fila:
            print(f'La fila con indice {indice_fila} ES IGUAL a la columna con índice {indice_columna}')
        else:
            print(f'La fila con indice {indice_fila} no coincide con la columna con índice {indice_columna}')



La fila con indice 0 no coincide con la columna con índice 0
La fila con indice 0 ES IGUAL a la columna con índice 1
La fila con indice 0 no coincide con la columna con índice 2
La fila con indice 0 no coincide con la columna con índice 3
La fila con indice 1 ES IGUAL a la columna con índice 0
La fila con indice 1 no coincide con la columna con índice 1
La fila con indice 1 no coincide con la columna con índice 2
La fila con indice 1 no coincide con la columna con índice 3
La fila con indice 2 no coincide con la columna con índice 0
La fila con indice 2 no coincide con la columna con índice 1
La fila con indice 2 ES IGUAL a la columna con índice 2
La fila con indice 2 no coincide con la columna con índice 3
La fila con indice 3 no coincide con la columna con índice 0
La fila con indice 3 no coincide con la columna con índice 1
La fila con indice 3 no coincide con la columna con índice 2
La fila con indice 3 no coincide con la columna con índice 3
